// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTaCS7zY9GkpsZ9oJXx706egZdeyjwBY',
    appId: '1:849647589718:web:78a6b95aa935c001c6def7',
    messagingSenderId: '849647589718',
    projectId: 'tal3-3b41a',
    authDomain: 'tal3-3b41a.firebaseapp.com',
    storageBucket: 'tal3-3b41a.firebasestorage.app',
    measurementId: 'G-1N6JGDXTVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmHnYBpqA3C2Z9e5jWMv4QzRusFmdKbCc',
    appId: '1:849647589718:android:870ed3432c5ba9c4c6def7',
    messagingSenderId: '849647589718',
    projectId: 'tal3-3b41a',
    storageBucket: 'tal3-3b41a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmIw1yaCt0-Fst6PcJW0ugq6PbkNNynhY',
    appId: '1:849647589718:ios:3d5582df0f4f4228c6def7',
    messagingSenderId: '849647589718',
    projectId: 'tal3-3b41a',
    storageBucket: 'tal3-3b41a.firebasestorage.app',
    iosBundleId: 'com.example.tal3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmIw1yaCt0-Fst6PcJW0ugq6PbkNNynhY',
    appId: '1:849647589718:ios:3d5582df0f4f4228c6def7',
    messagingSenderId: '849647589718',
    projectId: 'tal3-3b41a',
    storageBucket: 'tal3-3b41a.firebasestorage.app',
    iosBundleId: 'com.example.tal3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChTaCS7zY9GkpsZ9oJXx706egZdeyjwBY',
    appId: '1:849647589718:web:1f6b5958660854c4c6def7',
    messagingSenderId: '849647589718',
    projectId: 'tal3-3b41a',
    authDomain: 'tal3-3b41a.firebaseapp.com',
    storageBucket: 'tal3-3b41a.firebasestorage.app',
    measurementId: 'G-P42860RL3H',
  );
}
